import { Button, Divider, Input } from "antd";
import React, { useState, useEffect } from "react";
import { useHistory } from "react-router-dom";
import { AddressInput } from "../components";

function Deployer({ yourLocalBalance, readContracts, address, tx, writeContracts, localProvider }) {
  const history = useHistory();

  const [beneficiary, setBeneficiary] = useState();
  const [name, setName] = useState();

  useEffect(() => {
    if (address) { setBeneficiary(address); }
  }, [address]);

  if (!address) {
    return (
      <div>
        <div style={{ border: "1px solid #cccccc", padding: 16, width: 600, margin: "auto", marginTop: 64 }}>
          Connect your wallet to deploy a vault
        </div>
      </div>
    );
  }

  return (
    <div>
      <div style={{ border: "1px solid #cccccc", padding: 16, width: 600, margin: "auto", marginTop: 64 }}>
        <h2>Deploy a new endaoment Vault</h2>

        <h3>Vault Name</h3>
        <p>Name your vault</p>

        <Input value={name} onChange={e=> {
          setName(e.target.value);
        }} />

        <Divider />

        <h3>Beneficiary</h3>
        <p>This address will receive all interest generated by the beefy.finance vault</p>

        <AddressInput value={beneficiary} onChange={e=> {
          setBeneficiary(e.target.value);
        }} />

        <Divider />

        <h3>Currency</h3>

        <div>
          <img src="/dai.webp" /> DAI
        </div>

        <Divider />

        <Button
          style={{ marginTop: 8 }}
          onClick={async () => {
            tx(writeContracts.EndaomentFactory.deploy(beneficiary, name), (result, receipt) => {
              if (result.status === 1) {
                const newVaultAddress = `0x${result.logs[1].topics[1].substr(-40)}`;
                history.push(`/${newVaultAddress}`);
              }
            });
          }}
        >
          Deploy vault contract
        </Button>


      </div>
    </div>
  );
}

export default Deployer;
