import { useContractReader } from "eth-hooks";
import { Button, Card, DatePicker, Divider, Input, Progress, Slider, Spin, Switch } from "antd";
import { ethers } from "ethers";
import React, { useState, useEffect } from "react";
import { Link, useHistory } from "react-router-dom";
import { Address, AddressInput, TokenSelect } from "../components";

function Deployer({ yourLocalBalance, readContracts, address, tx, writeContracts, localProvider }) {
  const history = useHistory();

  const [beneficiary, setBeneficiary] = useState();
  const [currency, setCurrency] = useState();
  const [txHash, setTxHash] = useState();

  useEffect(() => {

    function wait(ms) {
      return new Promise(resolve => setTimeout(resolve, ms));
    }

    async function fetchReceipt() {
      try {
        const receipt = await localProvider.getTransactionReceipt(txHash);
        return receipt;
      } catch (err) {
        console.error(err);
      }
    }

    async function redirectOnConfirm()  {
      try {
        let receipt = null;
        do {
          wait(1000);
          receipt = await fetchReceipt();
        } while (receipt === null);

        const vaultAddress = receipt.logs[1].topics[0];
        history.push(`/${vaultAddress}`);
      } catch (err) {
        console.error(err)
      }

    }
    if (txHash) { redirectOnConfirm() }
  }, [txHash]);


  return (
    <div>
      <div style={{ border: "1px solid #cccccc", padding: 16, width: 600, margin: "auto", marginTop: 64 }}>
        <h2>Deploy a new endaoment Vault</h2>

        <h3>Beneficiary</h3>
        <p>This address will receive all interest generated by the beefy.finance vault</p>

        <AddressInput value={beneficiary} onChange={e=> {
          setBeneficiary(e.target.value);
        }} />

        <Button
          onClick={() => {
            setBeneficiary(address);
          }}
        >
          Set beneficiary to my address
        </Button>

        <Divider />

        <h3>Currency</h3>

        <TokenSelect
          chainId={1}
          onChange={setCurrency}
          localProvider={localProvider}
          nativeToken={{ name: 'Native token', symbol: 'ETH' }}
        />

        <Divider />


        <Button
          style={{ marginTop: 8 }}
          onClick={async () => {
            tx(writeContracts.EndaomentDeployer.deploy(beneficiary), (result, receipt) => {
              console.log('result: ', result)
              if (result.status === 1) {
                console.log('Confirmed with hash ', result.hash);
                //setTxHash(result.hash);
                const newVaultAddress = result.logs[1].topics[0];
                //history.push(`/${newVaultAddress}`);
                history.push(`/0x074800ec1d1cd0408b8bf6eed52e2ccac889ba45`);
              }
            });
          }}
        >
          Deploy vault contract
        </Button>


      </div>
    </div>
  );
}

export default Deployer;
